language: cpp
compiler: gcc
dist: trusty
before_install:
# C++14
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- wget -O boost_1_60_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.gz/download
- tar xzvf boost_1_60_0.tar.gz
- cd boost/
- sudo apt-get install build-essential g++
install: 
# C++14
- sudo ./bootstrap.sh --prefix=/usr/local
- sudo ./b2 install
- sudo ../
- sudo apt-get install -qq g++-6
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
before_script:
- sudo apt-get install libboost-test-dev -y
script:
  # Install Boost Test Framework 1.54
#- sudo apt-get install -y -qq libboost-test1.54-dev
#- cmake -DCMAKE_BUILD_TYPE=Release .
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T IpFilter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -umohammadwolf95:$BINTRAY_API_KEY "https://api.bintray.com/content/mohammadwolf95/ip_filter/ip_filters_package/$TRAVIS_BUILD_NUMBER/IpFilter-0.0.$TRAVIS_BUILD_NUMBER-Liux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
